// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: grpc/auction.proto

package auction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to place a bid
type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bidder        string                 `protobuf:"bytes,1,opt,name=bidder,proto3" json:"bidder,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_grpc_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{0}
}

func (x *Bid) GetBidder() string {
	if x != nil {
		return x.Bidder
	}
	return ""
}

func (x *Bid) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Acknowledgement message
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_grpc_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Empty request for queries
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpc_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{2}
}

// Result of highest current bid
type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bidder        string                 `protobuf:"bytes,1,opt,name=bidder,proto3" json:"bidder,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_grpc_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{3}
}

func (x *Result) GetBidder() string {
	if x != nil {
		return x.Bidder
	}
	return ""
}

func (x *Result) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_grpc_auction_proto protoreflect.FileDescriptor

const file_grpc_auction_proto_rawDesc = "" +
	"\n" +
	"\x12grpc/auction.proto\x12\aauction\"5\n" +
	"\x03Bid\x12\x16\n" +
	"\x06bidder\x18\x01 \x01(\tR\x06bidder\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\a\n" +
	"\x05Empty\"8\n" +
	"\x06Result\x12\x16\n" +
	"\x06bidder\x18\x01 \x01(\tR\x06bidder\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount2\x92\x01\n" +
	"\x0eAuctionService\x12&\n" +
	"\bPlaceBid\x12\f.auction.Bid\x1a\f.auction.Ack\x12*\n" +
	"\fPropagateBid\x12\f.auction.Bid\x1a\f.auction.Ack\x12,\n" +
	"\tGetResult\x12\x0e.auction.Empty\x1a\x0f.auction.ResultB*Z(github.com/Xerzes01/Auction/grpc;auctionb\x06proto3"

var (
	file_grpc_auction_proto_rawDescOnce sync.Once
	file_grpc_auction_proto_rawDescData []byte
)

func file_grpc_auction_proto_rawDescGZIP() []byte {
	file_grpc_auction_proto_rawDescOnce.Do(func() {
		file_grpc_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_auction_proto_rawDesc), len(file_grpc_auction_proto_rawDesc)))
	})
	return file_grpc_auction_proto_rawDescData
}

var file_grpc_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_auction_proto_goTypes = []any{
	(*Bid)(nil),    // 0: auction.Bid
	(*Ack)(nil),    // 1: auction.Ack
	(*Empty)(nil),  // 2: auction.Empty
	(*Result)(nil), // 3: auction.Result
}
var file_grpc_auction_proto_depIdxs = []int32{
	0, // 0: auction.AuctionService.PlaceBid:input_type -> auction.Bid
	0, // 1: auction.AuctionService.PropagateBid:input_type -> auction.Bid
	2, // 2: auction.AuctionService.GetResult:input_type -> auction.Empty
	1, // 3: auction.AuctionService.PlaceBid:output_type -> auction.Ack
	1, // 4: auction.AuctionService.PropagateBid:output_type -> auction.Ack
	3, // 5: auction.AuctionService.GetResult:output_type -> auction.Result
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_auction_proto_init() }
func file_grpc_auction_proto_init() {
	if File_grpc_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_auction_proto_rawDesc), len(file_grpc_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_auction_proto_goTypes,
		DependencyIndexes: file_grpc_auction_proto_depIdxs,
		MessageInfos:      file_grpc_auction_proto_msgTypes,
	}.Build()
	File_grpc_auction_proto = out.File
	file_grpc_auction_proto_goTypes = nil
	file_grpc_auction_proto_depIdxs = nil
}
